on: [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      # To use this action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          # Run a SAST scan using a supprted tool, Snyk as an example
          npx snyk auth ${{ secrets.SNYK_API_KEY }}
          ! npx snyk code test --sarif-file-output=/home/runner/report.json ./
        shell: bash -l {0}
      - name: Mobb action step
        uses: mobb-dev/action@v1
        with:
          report-file: "/home/runner/report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
